import { Image, StyleSheet, View } from 'react-native';
import { useTheme } from '../theme/ThemeProvider';

/**
 * The plaster tooth.
 *
 * The web token is an SVG filter blended into the ground — `feTurbulence`
 * drawn at opacity .4 and composited at `soft-light`. React Native has no
 * filters, no blend modes and no SVG-as-background, which is why the handoff
 * lists this as needing a shipped asset.
 *
 * It ships as a 64dp greyscale tile at 1×, 2× and 3×, generated by
 * `scripts/make-plaster.mjs` from a fixed seed. Greyscale and colourless on
 * purpose: it is drawn over whatever the ground happens to be, so one asset
 * serves daylight, lamplight and bright sun.
 *
 * ## What is lost, stated plainly
 *
 * `soft-light` is a real blend — it lightens where the backdrop is light and
 * darkens where it is dark, so the grain follows the surface. RN can only
 * composite `source-over`, so this is a flat overlay at low opacity. On the
 * pale daylight ground the two are close. On the lamplight ground the overlay
 * lifts the wall very slightly where soft-light would have deepened it, which
 * is why the lamplight opacity below is lower.
 *
 * The alternative is Skia, which would blend correctly and costs a large
 * native dependency for one texture. Not worth it until something else needs it.
 *
 * Difference is the whole point: **this must sit behind content and never over
 * it.** Render it as the first child of the ground view.
 */

/**
 * Tuned per theme rather than shared.
 *
 * Grain reads as noise on a dark wall far sooner than on a light one — the
 * same overlay that is texture at noon is dirt on the screen at 5am.
 */
const OPACITY = { daylight: 0.09, lamplight: 0.05, sun: 0.05 } as const;

export function Plaster(): React.ReactElement {
  const { theme } = useTheme();

  return (
    // Wrapped rather than set on the Image: ImageStyle has no pointerEvents,
    // and this covers the whole screen — a texture that swallowed taps would
    // break every control under it.
    <View style={StyleSheet.absoluteFill} pointerEvents="none">
      <Image
        // RN's asset pipeline resolves @2x/@3x by filename at bundle time, and
        // only through require(). An import cannot express the density set.
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        source={require('../../assets/plaster.png')}
        // Tiles rather than stretches. A stretched 64px noise tile across a
        // phone would be visible smears, not tooth.
        resizeMode="repeat"
        style={[StyleSheet.absoluteFill, { opacity: OPACITY[theme] }]}
        // Empty alt, not a missing one: this is texture, and a screen reader
        // announcing it would be reading the wallpaper aloud.
        alt=""
        accessible={false}
        accessibilityRole="none"
      />
    </View>
  );
}
