#!/usr/bin/env node
/**
 * Writes which commit a build came from, so a support ticket can name it.
 *
 * ## The gap this closes
 *
 * A ticket carries `app.version`, which is `version` in `app.json` — and that
 * string does not change between two preview builds a fortnight apart. So a
 * tester programme's first support conversation starts with "which build are
 * you on", which is the one question the whole machine-first bundle exists to
 * make unnecessary.
 *
 * ## Why a `.env` file rather than anything cleverer
 *
 * Expo's bundler inlines `process.env.EXPO_PUBLIC_*` as a literal
 * substitution on that exact member expression, and it reads `.env` files from
 * the app directory to find the values. That is the whole mechanism: write the
 * file, and the constant is baked into the bundle with no runtime lookup, no
 * native module, and nothing to fail on a device that is already failing.
 *
 * The alternative was `expo-constants` at runtime, and `version.ts` explains
 * why not: the value is needed while assembling a bundle on a handset that may
 * be about to crash again, which is the worst moment to call into native code.
 *
 * ## Where the commit comes from
 *
 * EAS sets `EAS_BUILD_GIT_COMMIT_HASH` on its builders, and this file is wired
 * to `eas-build-post-install` so it runs there without anybody remembering.
 * Locally it asks git. Neither is required: a build with no commit to name
 * says so rather than failing, because a stamp is diagnostics and refusing to
 * build over one would be the tail wagging the dog.
 */

import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const ENV_FILE = path.join(ROOT, 'apps/mobile/.env.local');

/** Seven characters: unambiguous in this repository and readable off a screen. */
function commit() {
  const fromEas = process.env.EAS_BUILD_GIT_COMMIT_HASH;
  if (fromEas) return fromEas.slice(0, 7);

  try {
    return execSync('git rev-parse --short=7 HEAD', { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

/**
 * Marked when the tree has uncommitted changes, because the commit alone would
 * be a lie about what was built — and the build somebody is holding is exactly
 * the one where that matters.
 */
function dirty() {
  if (process.env.EAS_BUILD_GIT_COMMIT_HASH) return false;
  try {
    return execSync('git status --porcelain', { encoding: 'utf8' }).trim() !== '';
  } catch {
    return false;
  }
}

const sha = commit();
const stamp = sha === '' ? '' : `${sha}${dirty() ? '+' : ''}`;

/**
 * Rewritten whole rather than appended to.
 *
 * The file is generated and gitignored (`.env*`), so nothing else owns a line
 * in it — and appending would leave every previous build's stamp behind, with
 * the last one silently winning.
 */
writeFileSync(ENV_FILE, `# Generated by scripts/stamp-build.mjs. Not committed.\nEXPO_PUBLIC_BUILD=${stamp}\n`);

console.log(stamp === '' ? 'stamp: no commit to name' : `stamp: ${stamp}`);
